### PR TITLE
fix ticket #3, #4

### PR DESCRIPTION
**Pull request by ruslangaripov**
I fixed tickets #3, #4.
By the way, 'OctoDroid' (GitHub client for Android platform) reports now that the project is crafted by C++  :sunglasses:

### CODE REVIEW

**Comment by ruslangaripov** [comment]
Check it out! :sunglasses: https://github.com/ruslangaripov/Arbor/releases/tag/v0.1-alpha

**Comment by Serg-Norseman** [comment]
On my comp is missing msvcp140.dll. Looking for how to install :)
...
Found. Still error starting

**Comment by Serg-Norseman** [comment]
With this advanced code of CPP-implementation, with the own infrastructure, I would this implementation were identified as a separate project because those who are able to use CPP-implementation - they don't need C# assemblies. For projects now needs separate releases

**Comment by Serg-Norseman** [comment]
I'm soon going to have developing another useful API. You never are interested in functions to convert dates between multiple basic calendars? Such modules have a lot. Many years ago I took one well-designed implementation (also in JavaScript) and has been ported to Delphi, then moved to C#. Not so long ago I get the task to bring one of the functions of this API to speed up the performance and accuracy.

**Comment by Serg-Norseman** [comment]
I looked at the source code... powerful work, cool bells and whistles... alas - it's not for my level in cpp.

**Comment by ruslangaripov** [comment]
_On my comp is missing msvcp140.dll. Looking for how to install_
The DLL is a part of MSFT VC++ 2015 runtime. You need to download [Microsoft Visual C++ 2015 redistributable runtime](https://go.microsoft.com/fwlink/?LinkId=615459)

_Still error starting_
What kind of error?

_those who are able to use CPP-implementation - they don't need C# assemblies._
I don't think so  :blush: Yes, I really don't like .NET :imp: But sometimes circumstances may force any C++ developer to use C#, you know :blush:

_For projects now needs separate releases_
My **uncompleted** C++ implementation is a logical part of the project. I believe it must stay within this repository! :octocat:

_You never are interested in functions to convert dates between multiple basic calendars?_
Let me take a look on it!  :eyes:

**Comment by Serg-Norseman** [comment]
_My uncompleted C++ implementation is a logical part of the project. I believe it must stay within this repository!_
;)

For sickness the second day I work in a zombie state. Today, when I saw the Number of programs cpp and flipped through the files, it seems I have a phase shift began ))) or at least "altered state of consciousness". I thought you were going to be crowded in that repository ;)

**Comment by Serg-Norseman** [comment]
_Let me take a look on it!_
I will prepare external assembly, will take away from the main project tests, etc... There's a couple of functions that, ideally, I will have to run with very high frequency... so I want to figure out how to optimize them to the limit.

**Pull request merged**
