### PR TITLE
Please review topic branch 'users/brigadir/ticket.9'

### PR DESCRIPTION
**Pull request by ruslangaripov**
# Ticket #9 is closed now
## Windows animation manager

The target C# code implements its own animation engine based on the Barnes-Hut simulation and some other stuff. It will be very hard to re-implement it as WAM custom interpolator. And since the “be WAM-ready” requirement was proposed by myself only and without having detailed information about what C# code did, I believe I can refuse this requirement now.
## SIMD

The library code does use SIMD.

The library code does use SSE, SSE2 and SSE3 **without checking CPU capabilities**.

Well, as for SSE and SSE2 I can repeat that while many years ago this could be a hasty action, I believe today one can use SSE/SSE2 without issuing the `CPUID` instruction. Because all x86-64 CPUs must support both of them. And it’s very hard to find a x86 CPU that knows nothing about SSE/SSE2 and... still does something necessary. May be one works for a Slackware instance. But I don’t target that OS right now. Someone can treat “not checking CPU capabilities” as a bad style and blame me despite the state of today CPU market. Well, I’m ready to add some `CPUID` calls, if one can change my mind.

And regarding SSE3. The same reason, sorry. It isn’t hard to abandon SSE3 instruction set in the code. It’s harder (for me) to find a CPU that lacks SSE3 support and able to support Windows 7 (at least).

The library code uses SSE4.1. And now it checks CPU capabilities before issuing `DPPS`, for example. As you can see – I can do that! :smiling_imp: I’m talking about checking CPU capabilities.

After all, read Intel® Architecture Instruction Set Extensions Programming Reference! It looks like the 512-bit SIMD vector SIMD extensions (AVX-512) “rules the world” while “128-bit _Legacy SSE_” just sucks! Just a joke, of course! :smiling_imp:

The library code doesn’t use AVX (yet).

I’ve simplified `vertex::swap` method by removing checks for QNaN. Neither `XORPS` fails on QNaN nor XOR-swapping of two QNaNs fails. XOR-swapping fails only when you swap **the same memory locations**. But I never do this by myself in the `swap` method, therefore I have made an “error” in a previous commit. And no one should call the `swap` method with two, the same vertices.
### Memory allocation

I have improved memory allocation service (so called “allocators”). For both aligned and unaligned memory. Some classes now overload `new` and `delete` operators “hiding” their alignment requirements.
## Rendering

A vertex and an edge have an optional “reference” to user-defined data. Currently it’s used by rendering engine to store Direct2D resources associated with vertex or edge.

Color of each edge is set to the `COLOR_WINDOWTEXT` by default. Color of each vertex is gray by default.

While C# code renders a vertex as a square, my C++ code renders it as an ellipse with dashed frame.

Currently the code implements **rendering only** – it doesn’t apply any n-body simulation algorithm. Therefore, edges and vertices may overlap. There are some assumptions in the library code, made by me without having complete knowledge about the algorithms, implemented in the C# code base. This is the algorithms I’m to move into my C++ code.

When rendering engine creates Direct2D resources owned by Direct2D device, the code also **may** create device-independent resources. While it looks like an error, this is not what it looks like. Because the code creates such resources only once, while it creates D2D device-dependent resource for each demand as usual.
### Arrow head rendering

Add some fun: do you think that rendering an arrow is an easy task? :smiling_imp: I thought the same. Now I don’t.
## Tests passed
- Per-monitor high DPI,
- Windows [7](https://drive.google.com/open?id=0B7VUFe2D4DjCTWVhcnlLRkU0ZEE), [8.1](https://drive.google.com/open?id=0B7VUFe2D4DjCX3VpbWRkSE5vTlE), [10](https://drive.google.com/open?id=0B7VUFe2D4DjCZHE1cXlpenRCWDg) (up to date).
## Tests not passed (because the code never had a chance)

```
[ ] Aggressive data/events loading,
[ ] Low resource simulation.
```

I’m waiting for Visual Studio 2015 Update 2 RTM where initialization order of list-initialization must be fixed. This will allow me to improve code of the `graph::addVertex` method.
## Thanks

I want to say “Thanks a lot!” to @Serg-Norseman :alien: For giving me an ability to recall geometry and algebra, trigonometric stuff and so on! For giving me that perfect sense when you craft low-level programming code!

### CODE REVIEW

**Comment by ruslangaripov** [comment]
Please feel free to check this out :smiling_imp: 
https://github.com/ruslangaripov/Arbor/releases/tag/v0.2-alpha

**Comment by ruslangaripov** [comment]
:confused: AppVer showed a strange error when I called `SetCurrentProcessExplicitAppUserModelID` via pointer to a function in the 'shell32.dll' loaded at run-time. It stated that I had a memory leak. But when I used `SetCurrentProcessExplicitAppUserModelID` as statically link function, the message gone. That's really strange. But since I target to Windows 7 and above I stuck with a static call.

Also

```
[x] Aggressive data/events loading
```

P.S. As you can see `v0.2-alpha' release doesn't include fixes from 9e8e466 commit.

**Comment by ruslangaripov** [comment]
`core.autocrlf` now set to `false` in my local development environment. :rage:

**Comment by Serg-Norseman** [comment]
This is a cool work!

**Comment by ruslangaripov** [comment]
Thanks! :smiling_imp:

**Pull request merged**
